site_name: Team Project (CSE, 2018)
docs_dir: docs
site_dir: site

copyright: Copyright &copy; 2026 Joe O'Regan

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joeaoregan/
    - icon: fontawesome/brands/github
      link: https://github.com/joeaoregan
    - icon: material/certificate
      link: https://www.credly.com/users/joe-o-regan
    - icon: simple/githubpages
      link: https://joeaoregan.github.io/      

theme:
  icon:
    admonition:
      note: material/account
      success: material/account
      warning: material/account
      danger: material/account
  logo: images/logo.png
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  name: material
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top

nav:
  - Home: 
    - index.md
    - External Links:    
      - Portfolio Home: https://joeaoregan.github.io/
      - Linkedin: https://www.linkedin.com/in/joeaoregan/
      - GitHub: https://github.com/joeaoregan
  - CA:
    - Overview: ca/index.md
    - Assignment: ca/assignment.md
    - Functional Requirements: ca/functional-requirements.md
    - User Stories: 
      - Overview: ca/user-stories/index.md
      - Manager: ca/user-stories/manager.md
      - Customer: ca/user-stories/customer.md
      - Front Desk: ca/user-stories/front-desk.md
      - Skipper: ca/user-stories/skipper.md
    - Users: ca/users.md
    - Definition of Done: ca/definition-of-done.md
    - Sprint 1: ca/sprint1.md
    - Sprint 2: ca/sprint2.md
    - Software Testing: 
      - Overview: ca/software-testing/index.md
      - Detailed Test Runs:
        - Test Run 1: ca/software-testing/test-run-1.md
        - Test Run 2: ca/software-testing/test-run-2.md
        - Test Run 3: ca/software-testing/test-run-3.md
        - Test Run 4: ca/software-testing/test-run-4.md
    - Screenshots: ca/screenshots.md
  - Labs: 
    - Overview: labs/index.md
    - Exercise 1: labs/exercise-1/index.md
    - Exercise 2:
      - Overview: labs/exercise-2/index.md
      - Exercise 2.1: labs/exercise-2/1/index.md
      - Exercise 2.2: labs/exercise-2/2/index.md
      - Exercise 2.3: labs/exercise-2/3/index.md
      - Exercise 2.4: labs/exercise-2/4/index.md
  - JSF Tags: 
    - Overview: jsf/tags/index.md
  - JSF App (Managed Beans): 
    - Overview: jsf/app/index.md
    - Intro to JSF Managed Beans: jsf/app/intro-to-managed-beans/index.md
    - Defining JSF Managed Beans: jsf/app/defining-jsf-managed-beans/index.md
    - Navigating between JSF Pages: jsf/app/navigating-between-jsf-pages/index.md
  - JSF Tables: 
    - Overview: jsf/tables/index.md
    - 1. A simple table displaying data: jsf/tables/exercise1.md
    - 2. Editing the table: jsf/tables/exercise2.md
    - 3. Deleting a row from the table: jsf/tables/exercise3.md
    - 4. Adding a row to the table: jsf/tables/exercise4.md
  - JSF Table Examples:
    - Overview: jsf/tables/examples/index.md
    - Eg 1 A simple table displaying data with style sheet: jsf/tables/examples/example1.md
    - Eg 2 Editing values in the table: jsf/tables/examples/example2.md
    - Eg 3 Delete a row from the table: jsf/tables/examples/example3.md
    - Eg 4 Adding a row to the table: jsf/tables/examples/example4.md
  - PrimeFaces:
    - Overview: primefaces/index.md
    - GitHub Links:
      - Code xhtml: https://github.com/joeaoregan/AIT-CSE-TeamProject/tree/master/Primefaces/WebContent
      - Code Beans: https://github.com/joeaoregan/AIT-CSE-TeamProject/tree/master/Primefaces/src/com/ait/jsf
  - Screenshots: ca/screenshots.md
      
  
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - bait-shop/*
              - jsf/*
              - index.md

repo_url: https://github.com/joeaoregan/AIT-CSE-TeamProject
repo_name: GitHub

site_url: https://joeaoregan.github.io/AIT-CSE-TeamProject